"use client";

import { useSettings } from "@/state/settings-state";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Body({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isDarkMode } = useSettings();
  return <body data-mode={(isDarkMode && "dark") || "light"}>{children}</body>;
}
