import RootState from "@/state";
import clsx from "clsx";
import "custom-react-scrollbar/dist/style.css";
import type { Metadata } from "next";
import { Cabin, Libre_Franklin } from "next/font/google";
import Body from "./body";
import "./globals.scss";

const header = Cabin({ subsets: ["latin"], variable: "--font-header" });
const body = Libre_Franklin({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(body.variable, header.variable)}>
      <RootState>
        <Body>{children}</Body>
      </RootState>
    </html>
  );
}
